#Application Server Port
server:
  port: 8081

application:
  backend:
    url: http://localhost:8081


#Application Time-Zone
spring:
  jackson:
    time-zone: Asia/Dhaka
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  cache:
      cache-names: book_library
      caffeine:
        spec: maximumSize=200,expireAfterWrite=900s

  #Application Database Setup
  datasource:
    url: jdbc:postgresql://localhost:5432/book_service
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        enable_lazy_load_no_trans: true                     # To avoid "failed to lazily initialize a collection of role could not initialize proxy - no session" error
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
    hibernate:
      ddl-auto: update
    show-sql: true

