#Application Server Port
server:
  port: 8221

cloud:
  aws:
    credentials:
      access-key: AKIAIOSFODNN7EXAMPLE
      secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    region:
      static: us-east-1
    stack:
      auto: false
aws:
  service-endpoint: http://localhost:4566

application:
  bucket:
    name: sjwpbd
  backend:
    url: https://sjwpbd.dhrubok.me
    ip: 172.104.176.86


#Application Time-Zone
spring:
  jackson:
    time-zone: Asia/Dhaka
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  main:
    allow-circular-references: true   # Some beans is depended upon another bean. By setting up this dependency, no compiler error will occur regarding this.

  #Application Database Setup
  datasource:
    url: jdbc:postgresql://localhost:5432/sjwpbd
    username: postgres
    password: 123four
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        enable_lazy_load_no_trans: true                     # To avoid "failed to lazily initialize a collection of role could not initialize proxy - no session" error
        format_sql: true
        jdbc:
          batch_size: 50
          order_inserts: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
 ## Logging
logging:
  config: src/main/resources/logback-production.xml
  level:
    org:
      hibernate: ERROR
      springframework:
        boot:
          autoconfigure: ERROR
        web: TRACE
        ws:
          soap:
            client: INFO
      apache:
        http: DEBUG
    

#OpenAPI Swagger-UI Custom Path
springdoc:
  swagger-ui:
    path: /documentation

